# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SR400_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 539)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.Graph = QtWidgets.QGraphicsView(Form)
        self.Graph.setObjectName("Graph")
        self.gridLayout.addWidget(self.Graph, 3, 0, 1, 3)
        self.ThreeTwoForm = QtWidgets.QGridLayout()
        self.ThreeTwoForm.setObjectName("ThreeTwoForm")
        self.TimeForm = QtWidgets.QSplitter(Form)
        self.TimeForm.setMaximumSize(QtCore.QSize(16777215, 34))
        self.TimeForm.setOrientation(QtCore.Qt.Horizontal)
        self.TimeForm.setObjectName("TimeForm")
        self.TimeLabel = QtWidgets.QLabel(self.TimeForm)
        self.TimeLabel.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.TimeVL = QtWidgets.QLabel(self.TimeForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.TimeVL.setFont(font)
        self.TimeVL.setObjectName("TimeVL")
        self.ThreeTwoForm.addWidget(self.TimeForm, 0, 0, 1, 1)
        self.StDevForm = QtWidgets.QSplitter(Form)
        self.StDevForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.StDevForm.setOrientation(QtCore.Qt.Horizontal)
        self.StDevForm.setObjectName("StDevForm")
        self.StDevLabel = QtWidgets.QLabel(self.StDevForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.StDevLabel.setFont(font)
        self.StDevLabel.setObjectName("StDevLabel")
        self.StDevVL = QtWidgets.QLabel(self.StDevForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.StDevVL.setFont(font)
        self.StDevVL.setObjectName("StDevVL")
        self.ThreeTwoForm.addWidget(self.StDevForm, 0, 1, 1, 1)
        self.PhotonForm = QtWidgets.QSplitter(Form)
        self.PhotonForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PhotonForm.setOrientation(QtCore.Qt.Horizontal)
        self.PhotonForm.setObjectName("PhotonForm")
        self.PhotonLabel = QtWidgets.QLabel(self.PhotonForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.PhotonLabel.setFont(font)
        self.PhotonLabel.setObjectName("PhotonLabel")
        self.PhotonVL = QtWidgets.QLabel(self.PhotonForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.PhotonVL.setFont(font)
        self.PhotonVL.setObjectName("PhotonVL")
        self.ThreeTwoForm.addWidget(self.PhotonForm, 1, 0, 1, 1)
        self.StErrForm = QtWidgets.QSplitter(Form)
        self.StErrForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.StErrForm.setOrientation(QtCore.Qt.Horizontal)
        self.StErrForm.setObjectName("StErrForm")
        self.StErrLabel = QtWidgets.QLabel(self.StErrForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.StErrLabel.setFont(font)
        self.StErrLabel.setObjectName("StErrLabel")
        self.StErrVL = QtWidgets.QLabel(self.StErrForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.StErrVL.setFont(font)
        self.StErrVL.setObjectName("StErrVL")
        self.ThreeTwoForm.addWidget(self.StErrForm, 1, 1, 1, 1)
        self.TotAvgForm = QtWidgets.QSplitter(Form)
        self.TotAvgForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TotAvgForm.setOrientation(QtCore.Qt.Horizontal)
        self.TotAvgForm.setObjectName("TotAvgForm")
        self.TotAvgLabel = QtWidgets.QLabel(self.TotAvgForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.TotAvgLabel.setFont(font)
        self.TotAvgLabel.setObjectName("TotAvgLabel")
        self.TotAvgVL = QtWidgets.QLabel(self.TotAvgForm)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.TotAvgVL.setFont(font)
        self.TotAvgVL.setObjectName("TotAvgVL")
        self.ThreeTwoForm.addWidget(self.TotAvgForm, 2, 0, 1, 1)
        self.BtnForm = QtWidgets.QGridLayout()
        self.BtnForm.setObjectName("BtnForm")
        self.StartBtn = QtWidgets.QPushButton(Form)
        self.StartBtn.setEnabled(True)
        self.StartBtn.setMinimumSize(QtCore.QSize(78, 37))
        self.StartBtn.setMaximumSize(QtCore.QSize(78, 37))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.BtnForm.addWidget(self.StartBtn, 0, 0, 1, 1)
        self.StopBtn = QtWidgets.QPushButton(Form)
        self.StopBtn.setMinimumSize(QtCore.QSize(75, 37))
        self.StopBtn.setMaximumSize(QtCore.QSize(75, 37))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StopBtn.setFont(font)
        self.StopBtn.setObjectName("StopBtn")
        self.BtnForm.addWidget(self.StopBtn, 0, 1, 1, 1)
        self.ThreeTwoForm.addLayout(self.BtnForm, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.ThreeTwoForm, 1, 2, 2, 1)
        self.TSETLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.TSETLabel.setFont(font)
        self.TSETLabel.setObjectName("TSETLabel")
        self.gridLayout.addWidget(self.TSETLabel, 1, 1, 1, 1)
        self.TSETForm = QtWidgets.QGridLayout()
        self.TSETForm.setObjectName("TSETForm")
        self.BaseLabel = QtWidgets.QLabel(Form)
        self.BaseLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.BaseLabel.setFont(font)
        self.BaseLabel.setObjectName("BaseLabel")
        self.TSETForm.addWidget(self.BaseLabel, 0, 0, 2, 1)
        self.BaseSlider = QtWidgets.QSlider(Form)
        self.BaseSlider.setMinimum(1)
        self.BaseSlider.setMaximum(9)
        self.BaseSlider.setSingleStep(1)
        self.BaseSlider.setProperty("value", 1)
        self.BaseSlider.setSliderPosition(1)
        self.BaseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BaseSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.BaseSlider.setTickInterval(1)
        self.BaseSlider.setObjectName("BaseSlider")
        self.TSETForm.addWidget(self.BaseSlider, 0, 1, 1, 1)
        self.BaseVL = QtWidgets.QLabel(Form)
        self.BaseVL.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.BaseVL.setFont(font)
        self.BaseVL.setObjectName("BaseVL")
        self.TSETForm.addWidget(self.BaseVL, 0, 2, 1, 1)
        self.ExponentVL = QtWidgets.QLabel(Form)
        self.ExponentVL.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.ExponentVL.setFont(font)
        self.ExponentVL.setObjectName("ExponentVL")
        self.TSETForm.addWidget(self.ExponentVL, 1, 2, 2, 1)
        self.ExponentLabel = QtWidgets.QLabel(Form)
        self.ExponentLabel.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ExponentLabel.setFont(font)
        self.ExponentLabel.setObjectName("ExponentLabel")
        self.TSETForm.addWidget(self.ExponentLabel, 2, 0, 1, 1)
        self.ExponentSlider = QtWidgets.QSlider(Form)
        self.ExponentSlider.setMaximum(11)
        self.ExponentSlider.setProperty("value", 0)
        self.ExponentSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ExponentSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.ExponentSlider.setTickInterval(1)
        self.ExponentSlider.setObjectName("ExponentSlider")
        self.TSETForm.addWidget(self.ExponentSlider, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.TSETForm, 2, 0, 1, 2)
        self.NPERForm = QtWidgets.QSplitter(Form)
        self.NPERForm.setMaximumSize(QtCore.QSize(16777215, 34))
        self.NPERForm.setOrientation(QtCore.Qt.Horizontal)
        self.NPERForm.setObjectName("NPERForm")
        self.NPERLabel = QtWidgets.QLabel(self.NPERForm)
        self.NPERLabel.setMinimumSize(QtCore.QSize(97, 34))
        self.NPERLabel.setMaximumSize(QtCore.QSize(97, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.NPERLabel.setFont(font)
        self.NPERLabel.setObjectName("NPERLabel")
        self.NPERSlider = QtWidgets.QSlider(self.NPERForm)
        self.NPERSlider.setMinimum(1)
        self.NPERSlider.setMaximum(2000)
        self.NPERSlider.setProperty("value", 1)
        self.NPERSlider.setOrientation(QtCore.Qt.Horizontal)
        self.NPERSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.NPERSlider.setTickInterval(100)
        self.NPERSlider.setObjectName("NPERSlider")
        self.NPERVL = QtWidgets.QLabel(self.NPERForm)
        self.NPERVL.setMaximumSize(QtCore.QSize(60, 34))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.NPERVL.setFont(font)
        self.NPERVL.setObjectName("NPERVL")
        self.gridLayout.addWidget(self.NPERForm, 0, 0, 2, 3)

        self.retranslateUi(Form)
        self.NPERSlider.valueChanged['int'].connect(self.NPERVL.setNum)
        self.BaseSlider.valueChanged['int'].connect(self.BaseVL.setNum)
        self.ExponentSlider.valueChanged['int'].connect(self.ExponentVL.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TimeLabel.setText(_translate("Form", "Time (s)"))
        self.TimeVL.setText(_translate("Form", "0"))
        self.StDevLabel.setText(_translate("Form", "St. Dev"))
        self.StDevVL.setText(_translate("Form", "0"))
        self.PhotonLabel.setText(_translate("Form", "Photons"))
        self.PhotonVL.setText(_translate("Form", "0"))
        self.StErrLabel.setText(_translate("Form", "St. Err"))
        self.StErrVL.setText(_translate("Form", "0"))
        self.TotAvgLabel.setText(_translate("Form", "Total Average"))
        self.TotAvgVL.setText(_translate("Form", "0"))
        self.StartBtn.setText(_translate("Form", "START"))
        self.StopBtn.setText(_translate("Form", "STOP"))
        self.TSETLabel.setText(_translate("Form", "Duration of Time Bins"))
        self.BaseLabel.setText(_translate("Form", "Base"))
        self.BaseVL.setText(_translate("Form", "0"))
        self.ExponentVL.setText(_translate("Form", "0"))
        self.ExponentLabel.setText(_translate("Form", "Exponent"))
        self.NPERLabel.setText(_translate("Form", "# of Bins"))
        self.NPERVL.setText(_translate("Form", "2000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

