# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SR400_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import numpy as np


class Ui_Form(object): 
    def __init__(self, Form):
        super().__init__()
        self.setupUi(Form)
        
    def setData(self):
        print("set data function")
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 630)
        self.Graph = PlotWidget(Form)
        self.Graph.setGeometry(QtCore.QRect(10, 150, 791, 471))
        self.Graph.setObjectName("Graph")
        self.Graph.plot(pen = None, symbol = 'o')
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 40, 251, 33))
        self.widget.setObjectName("widget")
        self.TSETForm = QtWidgets.QGridLayout(self.widget)
        self.TSETForm.setContentsMargins(0, 0, 0, 0)
        self.TSETForm.setObjectName("TSETForm")
        self.TSETLabel = QtWidgets.QLabel(self.widget)
        self.TSETLabel.setMinimumSize(QtCore.QSize(200, 22))
        self.TSETLabel.setMaximumSize(QtCore.QSize(200, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.TSETLabel.setFont(font)
        self.TSETLabel.setObjectName("TSETLabel")
        self.TSETForm.addWidget(self.TSETLabel, 0, 0, 1, 1)
        self.TSETBox = QtWidgets.QTextEdit(self.widget)
        self.TSETBox.setMinimumSize(QtCore.QSize(41, 31))
        self.TSETBox.setMaximumSize(QtCore.QSize(41, 31))
        self.TSETBox.setObjectName("TSETBox")
        self.TSETForm.addWidget(self.TSETBox, 0, 1, 1, 1)
        self.NPERForm = QtWidgets.QSplitter(Form)
        self.NPERForm.setGeometry(QtCore.QRect(10, 10, 801, 27))
        self.NPERForm.setOrientation(QtCore.Qt.Horizontal)
        self.NPERForm.setObjectName("NPERForm")
        self.NPERLabel = QtWidgets.QLabel(self.NPERForm)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.NPERLabel.setFont(font)
        self.NPERLabel.setObjectName("NPERLabel")
        self.NPERSlider = QtWidgets.QSlider(self.NPERForm)
        self.NPERSlider.setMinimumSize(QtCore.QSize(661, 27))
        self.NPERSlider.setMaximumSize(QtCore.QSize(661, 27))
        self.NPERSlider.setMinimum(1)
        self.NPERSlider.setMaximum(2000)
        self.NPERSlider.setProperty("value", 1)
        self.NPERSlider.setOrientation(QtCore.Qt.Horizontal)
        self.NPERSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.NPERSlider.setTickInterval(100)
        self.NPERSlider.setObjectName("NPERSlider")
        self.NPERVL = QtWidgets.QLabel(self.NPERForm)
        self.NPERVL.setMinimumSize(QtCore.QSize(16, 25))
        self.NPERVL.setMaximumSize(QtCore.QSize(51, 25))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.NPERVL.setFont(font)
        self.NPERVL.setObjectName("NPERVL")
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 90, 184, 51))
        self.widget1.setObjectName("widget1")
        self.BtnForm = QtWidgets.QGridLayout(self.widget1)
        self.BtnForm.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.BtnForm.setContentsMargins(0, 0, 0, 0)
        self.BtnForm.setObjectName("BtnForm")
        self.StartBtn = QtWidgets.QPushButton(self.widget1)
        self.StartBtn.setMinimumSize(QtCore.QSize(91, 51))
        self.StartBtn.setMaximumSize(QtCore.QSize(91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.BtnForm.addWidget(self.StartBtn, 0, 0, 1, 1)
        self.StopBtn = QtWidgets.QPushButton(self.widget1)
        self.StopBtn.setMinimumSize(QtCore.QSize(91, 51))
        self.StopBtn.setMaximumSize(QtCore.QSize(91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StopBtn.setFont(font)
        self.StopBtn.setObjectName("StopBtn")
        self.BtnForm.addWidget(self.StopBtn, 0, 1, 1, 1)
        self.TimeForm = QtWidgets.QSplitter(Form)
        self.TimeForm.setGeometry(QtCore.QRect(210, 90, 131, 41))
        self.TimeForm.setMinimumSize(QtCore.QSize(131, 41))
        self.TimeForm.setOrientation(QtCore.Qt.Horizontal)
        self.TimeForm.setObjectName("TimeForm")
        self.TimeLabel = QtWidgets.QLabel(self.TimeForm)
        self.TimeLabel.setMinimumSize(QtCore.QSize(105, 41))
        self.TimeLabel.setMaximumSize(QtCore.QSize(105, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.TimeVL = QtWidgets.QLabel(self.TimeForm)
        self.TimeVL.setMinimumSize(QtCore.QSize(19, 41))
        self.TimeVL.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.TimeVL.setFont(font)
        self.TimeVL.setObjectName("TimeVL")
        self.PhotonForm = QtWidgets.QSplitter(Form)
        self.PhotonForm.setGeometry(QtCore.QRect(270, 40, 131, 41))
        self.PhotonForm.setMinimumSize(QtCore.QSize(131, 41))
        self.PhotonForm.setOrientation(QtCore.Qt.Horizontal)
        self.PhotonForm.setObjectName("PhotonForm")
        self.PhotonLabel = QtWidgets.QLabel(self.PhotonForm)
        self.PhotonLabel.setMinimumSize(QtCore.QSize(103, 41))
        self.PhotonLabel.setMaximumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.PhotonLabel.setFont(font)
        self.PhotonLabel.setObjectName("PhotonLabel")
        self.PhotonVL = QtWidgets.QLabel(self.PhotonForm)
        self.PhotonVL.setMinimumSize(QtCore.QSize(19, 41))
        self.PhotonVL.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.PhotonVL.setFont(font)
        self.PhotonVL.setObjectName("PhotonVL")
        self.TotAvgForm = QtWidgets.QSplitter(Form)
        self.TotAvgForm.setGeometry(QtCore.QRect(500, 40, 201, 41))
        self.TotAvgForm.setMinimumSize(QtCore.QSize(201, 41))
        self.TotAvgForm.setOrientation(QtCore.Qt.Horizontal)
        self.TotAvgForm.setObjectName("TotAvgForm")
        self.TotAvgLabel = QtWidgets.QLabel(self.TotAvgForm)
        self.TotAvgLabel.setMinimumSize(QtCore.QSize(175, 41))
        self.TotAvgLabel.setMaximumSize(QtCore.QSize(175, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.TotAvgLabel.setFont(font)
        self.TotAvgLabel.setObjectName("TotAvgLabel")
        self.TotAvgVL = QtWidgets.QLabel(self.TotAvgForm)
        self.TotAvgVL.setMinimumSize(QtCore.QSize(19, 41))
        self.TotAvgVL.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.TotAvgVL.setFont(font)
        self.TotAvgVL.setObjectName("TotAvgVL")
        self.StDevForm = QtWidgets.QSplitter(Form)
        self.StDevForm.setGeometry(QtCore.QRect(440, 90, 121, 41))
        self.StDevForm.setMinimumSize(QtCore.QSize(121, 41))
        self.StDevForm.setOrientation(QtCore.Qt.Horizontal)
        self.StDevForm.setObjectName("StDevForm")
        self.StDevLabel = QtWidgets.QLabel(self.StDevForm)
        self.StDevLabel.setMinimumSize(QtCore.QSize(91, 41))
        self.StDevLabel.setMaximumSize(QtCore.QSize(91, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.StDevLabel.setFont(font)
        self.StDevLabel.setObjectName("StDevLabel")
        self.StDevVL = QtWidgets.QLabel(self.StDevForm)
        self.StDevVL.setMinimumSize(QtCore.QSize(19, 41))
        self.StDevVL.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.StDevVL.setFont(font)
        self.StDevVL.setObjectName("StDevVL")
        self.StErrForm = QtWidgets.QSplitter(Form)
        self.StErrForm.setGeometry(QtCore.QRect(640, 90, 101, 41))
        self.StErrForm.setMinimumSize(QtCore.QSize(101, 41))
        self.StErrForm.setMaximumSize(QtCore.QSize(16777215, 41))
        self.StErrForm.setOrientation(QtCore.Qt.Horizontal)
        self.StErrForm.setObjectName("StErrForm")
        self.StErrLabel = QtWidgets.QLabel(self.StErrForm)
        self.StErrLabel.setMinimumSize(QtCore.QSize(75, 41))
        self.StErrLabel.setMaximumSize(QtCore.QSize(75, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.StErrLabel.setFont(font)
        self.StErrLabel.setObjectName("StErrLabel")
        self.StErrVL = QtWidgets.QLabel(self.StErrForm)
        self.StErrVL.setMinimumSize(QtCore.QSize(19, 41))
        self.StErrVL.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.StErrVL.setFont(font)
        self.StErrVL.setObjectName("StErrVL")

        self.retranslateUi(Form)
        self.NPERSlider.valueChanged['int'].connect(self.NPERVL.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        Form.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TSETLabel.setText(_translate("Form", "Duration of Time Bins (s)"))
        self.TSETBox.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9e11</p></body></html>"))
        self.NPERLabel.setText(_translate("Form", "# of Bins"))
        self.NPERVL.setText(_translate("Form", "0"))
        self.StartBtn.setText(_translate("Form", "START"))
        self.StopBtn.setText(_translate("Form", "STOP"))
        self.TimeLabel.setText(_translate("Form", "Time (s)"))
        self.TimeVL.setText(_translate("Form", "0"))
        self.PhotonLabel.setText(_translate("Form", "Photons"))
        self.PhotonVL.setText(_translate("Form", "0"))
        self.TotAvgLabel.setText(_translate("Form", "Total Average"))
        self.TotAvgVL.setText(_translate("Form", "0"))
        self.StDevLabel.setText(_translate("Form", "St. Dev"))
        self.StDevVL.setText(_translate("Form", "0"))
        self.StErrLabel.setText(_translate("Form", "St. Err"))
        self.StErrVL.setText(_translate("Form", "0"))

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
"""
